name: CI Pipeline for Mern Stack Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Show repo files
        run: ls -la

      - name: Verify Node and npm versions
        run: |
          node -v
          npm -v